repos:
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.5
    hooks:
      - id: nbqa-black
        additional_dependencies: [black==24.4.2]
      - id: nbqa-pyupgrade
        additional_dependencies: [pyupgrade==3.16.0]
      - id: nbqa-isort
        args: [--profile=black]
        additional_dependencies: [isort==5.13.2]
